export const achievementList = [
  {
    id: 1,
    name: "Finish 25 easy levels of Sudoku",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_brown.png`,
    alt: "Brown Sudoku Achievement",
  },
  {
    id: 2,
    name: "Finish 50 medium levels of Sudoku",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_silver.png`,
    alt: "Silver Sudoku Achievement",
  },
  {
    id: 3,
    name: "Finish 75 hard levels of Sudoku",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_gold.png`,
    alt: "Gold Sudoku Achievement",
  },
  {
    id: 4,
    name: "Finish 100 levels of Sudoku",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_diamond.png`,
    alt: "Diamond Sudoku Achievement",
  },
  {
    id: 5,
    name: "Finish 10 easy levels of Crossword",
    img: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_brown.png`,
    alt: "Brown Crossword Achievement",
  },
  {
    id: 6,
    name: "Finish 20 medium levels of Crossword",
    img: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_silver.png`,
    alt: "Silver Crossword Achievement",
  },
  {
    id: 7,
    name: "Finish 30 hard levels of Crossword",
    img: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_gold.png`,
    alt: "Gold Crossword Achievement",
  },
  {
    id: 8,
    name: "Finish 40 impossible levels of Crossword",
    img: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_diamond.png`,
    alt: "Diamond Crossword Achievement",
  },
  {
    id: 9,
    name: "Finish 25 levels of Memory",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_brown.png`,
    alt: "Brown Memory Achievement",
  },
  {
    id: 10,
    name: "Finish 50 levels of Memory",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_silver.png`,
    alt: "Silver Memory Achievement",
  },
  {
    id: 11,
    name: "Finish 75 levels of Memory",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_gold.png`,
    alt: "Gold Memory Achievement",
  },
  {
    id: 12,
    name: "Finish 100 levels of Memory",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_diamond.png`,
    alt: "Diamond Memory Achievement",
  },
  {
    id: 13,
    name: "Finish 10 easy levels of 2048",
    img: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_brown.png`,
    alt: "Brown 2048 Achievement",
  },
  {
    id: 14,
    name: "Finish 20 medium levels of 2048",
    img: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_silver.png`,
    alt: "Silver 2048 Achievement",
  },
  {
    id: 15,
    name: "Finish 30 hard levels of 2048",
    img: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_gold.png`,
    alt: "Gold 2048 Achievement",
  },
  {
    id: 16,
    name: "Finish 50 hard levels of 2048",
    img: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_diamond.png`,
    alt: "Diamond 2048 Achievement",
  },
  {
    id: 17,
    name: "Finish 10 easy levels of Minesweeper",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_brown.png`,
    alt: "Brown Minesweeper Achievement",
  },
  {
    id: 18,
    name: "Finish 20 medium levels of Minesweeper",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_silver.png`,
    alt: "Silver Minesweeper Achievement",
  },
  {
    id: 19,
    name: "Finish 20 medium levels of Minesweeper",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_gold.png`,
    alt: "Gold Minesweeper Achievement",
  },
  {
    id: 20,
    name: "Finish 50 hard levels of Minesweeper",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_diamond.png`,
    alt: "Diamond Minesweeper Achievement",
  },
  {
    id: 21,
    name: "Score 30 points in Snake",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_brown.png`,
    alt: "Brown Snake Achievement",
  },
  {
    id: 22,
    name: "Score 50 points in Snake",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_silver.png`,
    alt: "Silver Snake Achievement",
  },
  {
    id: 23,
    name: "Score 70 points in Snake",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_gold.png`,
    alt: "Gold Snake Achievement",
  },
  {
    id: 24,
    name: "Score 100 points in Snake",
    img: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_diamond.png`,
    alt: "Diamond Snake Achievement",
  },
  {
    id: 25,
    name: "Complete 25 levels of Maze with a minimum board size of 5x5",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_brown.png`,
    alt: "Brown Maze Achievement",
  },
  {
    id: 26,
    name: "Complete 20 levels of Maze with a minimum board size of 20x20",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_silver.png`,
    alt: "Silver Maze Achievement",
  },
  {
    id: 27,
    name: "Complete 15 levels of Maze with a minimum board size of 30x30",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_gold.png`,
    alt: "Gold Maze Achievement",
  },
  {
    id: 28,
    name: "Complete 10 levels of Maze with a minimum board size of 35x35",
    img: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_diamond.png`,
    alt: "Diamond Maze Achievement",
  },
  {
    id: 29,
    name: "Score 50 points in Ball in the hole",
    img: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_brown.png`,
    alt: "Brown Ball in the hole Achievement",
  },
  {
    id: 30,
    name: "Score 40 points in Ball in the hole",
    img: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_silver.png`,
    alt: "Silver Ball in the hole Achievement",
  },
  {
    id: 31,
    name: "Score 30 points in Ball in the hole",
    img: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_gold.png`,
    alt: "Gold Ball in the hole Achievement",
  },
  {
    id: 32,
    name: "Score 20 points in Ball in the hole",
    img: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_diamond.png`,
    alt: "Diamond Ball in the hole Achievement",
  },
  {
    id: 33,
    name: "Answer 40 Quiz questions correctly",
    img: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_brown.png`,
    alt: "Brown Quiz Achievement",
  },
  {
    id: 34,
    name: "Answer 80 Quiz questions correctly",
    img: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_silver.png`,
    alt: "Silver Quiz Achievement",
  },
  {
    id: 35,
    name: "Answer 120 Quiz questions correctly",
    img: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_gold.png`,
    alt: "Gold Quiz Achievement",
  },
  {
    id: 36,
    name: "Answer 200 Quiz questions correctly",
    img: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_diamond.png`,
    alt: "Diamond Quiz Achievement",
  },
  {
    id: 37,
    name: "Win 10 games of Tic Tac Toe",
    img: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_brown.png`,
    alt: "Brown Tic Tac Toe Achievement",
  },
  {
    id: 38,
    name: "Win 20 games of Tic Tac Toe",
    img: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_silver.png`,
    alt: "Silver Tic Tac Toe Achievement",
  },
  {
    id: 39,
    name: "Win 40 games of Tic Tac Toe",
    img: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_gold.png`,
    alt: "Gold Tic Tac Toe Achievement",
  },
  {
    id: 40,
    name: "Win 80 games of Tic Tac Toe",
    img: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_diamond.png`,
    alt: "Diamond Tic Tac Toe Achievement",
  },
];
