export const achievementList = [
  {
    id: 1,
    name: "Finish levels of Sudoku",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/SudokuImages/Sudoku_diamond.png`,
    },
    alt: "Sudoku Achievement",
    levels: {
      brown: "Finish 25 levels of Sudoku",
      silver: "Finish 50 levels of Sudoku",
      gold: "Finish 75 levels of Sudoku",
      diamond: "Finish 100 levels of Sudoku",
    },
  },
  {
    id: 2,
    name: "Finish levels of Crossword",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/CrosswordImages/Crossword_diamond.png`,
    },
    alt: "Crossword Achievement",
    levels: {
      brown: "Finish 10 easy levels of Crossword",
      silver: "Finish 20 medium levels of Crossword",
      gold: "Finish 30 hard levels of Crossword",
      diamond: "Finish 40 impossible levels of Crossword",
    },
  },
  {
    id: 3,
    name: "Finish levels of Memory",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/MemoryImages/Memory_diamond.png`,
    },
    alt: "Memory Achievement",
    levels: {
      brown: "Finish 25 levels of Memory",
      silver: "Finish 50 levels of Memory",
      gold: "Finish 75 levels of Memory",
      diamond: "Finish 100 levels of Memory",
    },
  },
  {
    id: 4,
    name: "Finish levels of 2048",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/Game2048Images/Game2048_diamond.png`,
    },
    alt: "2048 Game Achievement",
    levels: {
      brown: "Finish 10 easy levels of 2048",
      silver: "Finish 20 medium levels of 2048",
      gold: "Finish 30 hard levels of 2048",
      diamond: "Finish 50 hard levels of 2048",
    },
  },
  {
    id: 5,
    name: "Finish levels of Minesweeper",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/MinesweeperImages/Minesweeper_diamond.png`,
    },
    alt: "Minesweeper Game Achievement",
    levels: {
      brown: "Finish 10 easy levels of Minesweeper",
      silver: "Finish 20 medium levels of Minesweeper",
      gold: "Finish 30 hard levels of Minesweeper",
      diamond: "Finish 50 hard levels of Minesweeper",
    },
  },
  {
    id: 6,
    name: "Score in Snake",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/SnakeImages/Snake_diamond.png`,
    },
    alt: "Snake Game Achievement",
    levels: {
      brown: "Score 30 points in Snake",
      silver: "Score 50 points in Snake",
      gold: "Score 70 points in Snake",
      diamond: "Score 100 points in Snake",
    },
  },
  {
    id: 7,
    name: "Complete Maze levels",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/MazeImages/Maze_diamond.png`,
    },
    alt: "Maze Game Achievement",
    levels: {
      brown: "Complete 25 levels of Maze with a minimum board size of 5x5",
      silver: "Complete 20 levels of Maze with a minimum board size of 20x20",
      gold: "Complete 15 levels of Maze with a minimum board size of 30x30",
      diamond: "Complete 10 levels of Maze with a minimum board size of 35x35",
    },
  },
  {
    id: 8,
    name: "Score in Ball in the hole",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/BallInTheHoleImages/Ball_in_the_hole_diamond.png`,
    },
    alt: "Ball in the Hole Game Achievement",
    levels: {
      brown: "Score 50 points in Ball in the hole",
      silver: "Score 40 points in Ball in the hole",
      gold: "Score 30 points in Ball in the hole",
      diamond: "Score 20 points in Ball in the hole",
    },
  },
  {
    id: 9,
    name: "Answer Quiz questions correctly",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/QuizImages/Quiz_diamond.png`,
    },
    alt: "Quiz Game Achievement",
    levels: {
      brown: "Answer 40 Quiz questions correctly",
      silver: "Answer 80 Quiz questions correctly",
      gold: "Answer 120 Quiz questions correctly",
      diamond: "Answer 200 Quiz questions correctly",
    },
  },
  {
    id: 10,
    name: "Win games of Tic Tac Toe",
    images: {
      brown: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_brown.png`,
      silver: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_silver.png`,
      gold: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_gold.png`,
      diamond: `${process.env.PUBLIC_URL}/AchievementImages/TicTacToeImages/Tic_tac_toe_diamond.png`,
    },
    alt: "Tic Tac Toe Game Achievement",
    levels: {
      brown: "Win 10 games of Tic Tac Toe",
      silver: "Win 20 games of Tic Tac Toe",
      gold: "Win 40 games of Tic Tac Toe",
      diamond: "Win 80 games of Tic Tac Toe",
    },
  },
];
